### ISSUE TITLE
NoSuchMethodError getOutputDirectory() with Gradle Plugin 4.0.0 

### ISSUE THREAD

**Issue by omarmiatello** [oliviergauthier/gradle-appcenter-plugin#43] opened 2020-01-03 10:19 UTC
My configuration:
```
dependencies {
    classpath "com.android.tools.build:gradle:4.0.0-alpha07"
}
```

```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1-milestone-2-all.zip
```

Error:
```
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Ljava/io/File;
	at com.betomorrow.gradle.appcenter.AppCenterPlugin.handleVariant(AppCenterPlugin.kt:48)
	at com.betomorrow.gradle.appcenter.AppCenterPlugin.access$handleVariant(AppCenterPlugin.kt:12)
	at com.betomorrow.gradle.appcenter.AppCenterPlugin$apply$$inlined$with$lambda$1.execute(AppCenterPlugin.kt:29)
	at com.betomorrow.gradle.appcenter.AppCenterPlugin$apply$$inlined$with$lambda$1.execute(AppCenterPlugin.kt:12)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:152)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:92)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	... 125 more
```

Line in the source:

https://github.com/oliviergauthier/gradle-appcenter-plugin/blob/1ffd9f96841e86106a374aa4b6672490c46a1a4f/src/main/kotlin/com/betomorrow/gradle/appcenter/AppCenterPlugin.kt#L48

**Comment by oliviergauthier** [comment] 2020-01-05 08:29
Duplicate of #41

**Closed by oliviergauthier** 2020-01-05 08:29 UTC
Labels: enhancement
