### ISSUE TITLE
Deprecated AppCenter APIs

### ISSUE THREAD

**Issue by hf** [oliviergauthier/gradle-appcenter-plugin#63] opened 2021-04-07 10:39 UTC
This plugin uses deprecated AppCenter APIs as seen here https://openapi.appcenter.ms/#/distribute/releaseUploads_create and https://github.com/oliviergauthier/gradle-appcenter-plugin/blob/32aafa583aa843347663b5db7733b5586d655814/src/main/kotlin/com/betomorrow/gradle/appcenter/infra/AppCenterAPI.kt#L12-L24

**Comment by jasonschroeder-sfdc** [comment] 2021-04-19 17:01
This might be a duplicate of #60 , which was fixed by #62 ?

**Closed** 2021-04-26 19:21 UTC
